/**
 * Task.java
 * ─────────────────────────────────────────────────────────────────────────────
 * Represents a single Task entity in the Persistent Task Management System.
 *
 * Design Principles Applied:
 *   - Encapsulation  : All fields are private; accessed via getters/setters
 *   - Serialization  : toFileString() / fromFileString() handle file I/O format
 *   - Separation     : This class only models data — no I/O or menu logic here
 *
 * File Format (one task per line, pipe-delimited):
 *   taskId|taskTitle|taskDescription|taskStatus
 *
 * Author  : [Your Name]
 * Project : Persistent Task Management System
 * Version : 1.0
 * ─────────────────────────────────────────────────────────────────────────────
 */
public class Task {

    // ─────────────────────────────────────────────
    //  Constants
    // ─────────────────────────────────────────────

    /** Delimiter used when writing a task to / reading from tasks.txt */
    static final String DELIMITER = "|";

    /** Regex-safe version of the delimiter for String.split() */
    static final String DELIMITER_REGEX = "\\|";

    // ─────────────────────────────────────────────
    //  Fields (Private — Encapsulation)
    // ─────────────────────────────────────────────

    private int    taskId;           // Auto-generated unique identifier
    private String taskTitle;        // Short, descriptive task name
    private String taskDescription;  // Detailed explanation of the task
    private String taskStatus;       // "Pending" | "In Progress" | "Completed"

    // ─────────────────────────────────────────────
    //  Constructor
    // ─────────────────────────────────────────────

    /**
     * Creates a fully-initialised Task object.
     *
     * @param taskId          Unique ID (auto-generated by TaskManager)
     * @param taskTitle       Short title of the task
     * @param taskDescription Detailed description of what needs to be done
     * @param taskStatus      Current status of the task
     */
    public Task(int taskId, String taskTitle, String taskDescription, String taskStatus) {
        this.taskId          = taskId;
        this.taskTitle       = taskTitle;
        this.taskDescription = taskDescription;
        this.taskStatus      = taskStatus;
    }

    // ─────────────────────────────────────────────
    //  Getters
    // ─────────────────────────────────────────────

    public int    getTaskId()          { return taskId; }
    public String getTaskTitle()       { return taskTitle; }
    public String getTaskDescription() { return taskDescription; }
    public String getTaskStatus()      { return taskStatus; }

    // ─────────────────────────────────────────────
    //  Setters
    // ─────────────────────────────────────────────

    public void setTaskTitle(String taskTitle)             { this.taskTitle       = taskTitle; }
    public void setTaskDescription(String taskDescription) { this.taskDescription = taskDescription; }
    public void setTaskStatus(String taskStatus)           { this.taskStatus      = taskStatus; }

    // ─────────────────────────────────────────────
    //  File Serialisation Helpers
    // ─────────────────────────────────────────────

    /**
     * Serialises this Task into a single pipe-delimited line for file storage.
     *
     * Example output:
     *   3|Deploy to AWS|Set up EC2 instance and configure environment|Pending
     *
     * @return Pipe-delimited string representation of this task
     */
    public String toFileString() {
        return taskId + DELIMITER + taskTitle + DELIMITER + taskDescription + DELIMITER + taskStatus;
    }

    /**
     * Deserialises a pipe-delimited file line back into a Task object.
     * Returns null if the line is malformed, preventing data corruption.
     *
     * @param line A single line read from tasks.txt
     * @return     A fully reconstructed Task, or null if the line is invalid
     */
    public static Task fromFileString(String line) {
        // Guard against null or blank lines (e.g. trailing newline at end of file)
        if (line == null || line.trim().isEmpty()) return null;

        String[] parts = line.split(DELIMITER_REGEX);

        // Expect exactly 4 fields: id, title, description, status
        if (parts.length != 4) return null;

        try {
            int    id          = Integer.parseInt(parts[0].trim());
            String title       = parts[1].trim();
            String description = parts[2].trim();
            String status      = parts[3].trim();

            // Reject obviously empty core fields
            if (title.isEmpty() || description.isEmpty() || status.isEmpty()) return null;

            return new Task(id, title, description, status);

        } catch (NumberFormatException e) {
            // The ID field was not a valid integer — skip this line
            return null;
        }
    }

    // ─────────────────────────────────────────────
    //  toString (for debugging / logging)
    // ─────────────────────────────────────────────

    @Override
    public String toString() {
        return "Task{id=" + taskId
             + ", title='"       + taskTitle       + '\''
             + ", description='" + taskDescription + '\''
             + ", status='"      + taskStatus      + "'}";
    }
}
